name: Review Hero Auto-Fix
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  actions: read
  contents: write
  pull-requests: write
  workflows: write # special permission just in this repo so we can be meta about it

jobs:
  auto-fix:
    uses: beyondessential/review-hero/.github/workflows/auto-fix.yml@main
    secrets: inherit
